project_id = "vbkbbfeujqmvgmmhmeao"

[functions.kanban-api]
verify_jwt = false

[functions.fiscal-news]
verify_jwt = false

[functions.ticket-summary]
verify_jwt = false

[functions.spellcheck-ptbr]
verify_jwt = false
