/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AtualizacoesRouteImport } from './routes/atualizacoes'
import { Route as BaseDeConhecimentoRouteImport } from './routes/base-de-conhecimento'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as FrotaRouteImport } from './routes/frota'
import { Route as IniciarHadronRouteImport } from './routes/iniciar-hadron'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as KanbanDashboardRouteImport } from './routes/kanban-dashboard'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as VersoesRouteImport } from './routes/versoes'
import { Route as BaseDeConhecimentoIndexRouteImport } from './routes/base-de-conhecimento.index'
import { Route as BaseDeConhecimentoSlugRouteImport } from './routes/base-de-conhecimento.$slug'
import { Route as ChamadosNovoRouteImport } from './routes/chamados.novo'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes.$clienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizacoesRoute = AtualizacoesRouteImport.update({
  id: '/atualizacoes',
  path: '/atualizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseDeConhecimentoRoute = BaseDeConhecimentoRouteImport.update({
  id: '/base-de-conhecimento',
  path: '/base-de-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaRoute = FrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarHadronRoute = IniciarHadronRouteImport.update({
  id: '/iniciar-hadron',
  path: '/iniciar-hadron',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanDashboardRoute = KanbanDashboardRouteImport.update({
  id: '/kanban-dashboard',
  path: '/kanban-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const VersoesRoute = VersoesRouteImport.update({
  id: '/versoes',
  path: '/versoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseDeConhecimentoIndexRoute = BaseDeConhecimentoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseDeConhecimentoRoute,
} as any)
const BaseDeConhecimentoSlugRoute = BaseDeConhecimentoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BaseDeConhecimentoRoute,
} as any)
const ChamadosNovoRoute = ChamadosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ChamadosRoute,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/base-de-conhecimento': typeof BaseDeConhecimentoRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/chamados': typeof ChamadosRouteWithChildren
  '/frota': typeof FrotaRoute
  '/iniciar-hadron': typeof IniciarHadronRoute
  '/kanban': typeof KanbanRoute
  '/kanban-dashboard': typeof KanbanDashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/versoes': typeof VersoesRoute
  '/base-de-conhecimento/$slug': typeof BaseDeConhecimentoSlugRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/base-de-conhecimento/': typeof BaseDeConhecimentoIndexRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/calendario': typeof CalendarioRoute
  '/chamados': typeof ChamadosRouteWithChildren
  '/frota': typeof FrotaRoute
  '/iniciar-hadron': typeof IniciarHadronRoute
  '/kanban': typeof KanbanRoute
  '/kanban-dashboard': typeof KanbanDashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/versoes': typeof VersoesRoute
  '/base-de-conhecimento/$slug': typeof BaseDeConhecimentoSlugRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/base-de-conhecimento': typeof BaseDeConhecimentoIndexRoute
  '/clientes': typeof ClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/base-de-conhecimento': typeof BaseDeConhecimentoRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/chamados': typeof ChamadosRouteWithChildren
  '/frota': typeof FrotaRoute
  '/iniciar-hadron': typeof IniciarHadronRoute
  '/kanban': typeof KanbanRoute
  '/kanban-dashboard': typeof KanbanDashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/versoes': typeof VersoesRoute
  '/base-de-conhecimento/$slug': typeof BaseDeConhecimentoSlugRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/base-de-conhecimento/': typeof BaseDeConhecimentoIndexRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/atualizacoes'
    | '/base-de-conhecimento'
    | '/calendario'
    | '/chamados'
    | '/frota'
    | '/iniciar-hadron'
    | '/kanban'
    | '/kanban-dashboard'
    | '/minha-conta'
    | '/versoes'
    | '/base-de-conhecimento/$slug'
    | '/chamados/novo'
    | '/clientes/$clienteId'
    | '/base-de-conhecimento/'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/atualizacoes'
    | '/calendario'
    | '/chamados'
    | '/frota'
    | '/iniciar-hadron'
    | '/kanban'
    | '/kanban-dashboard'
    | '/minha-conta'
    | '/versoes'
    | '/base-de-conhecimento/$slug'
    | '/chamados/novo'
    | '/clientes/$clienteId'
    | '/base-de-conhecimento'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/atualizacoes'
    | '/base-de-conhecimento'
    | '/calendario'
    | '/chamados'
    | '/frota'
    | '/iniciar-hadron'
    | '/kanban'
    | '/kanban-dashboard'
    | '/minha-conta'
    | '/versoes'
    | '/base-de-conhecimento/$slug'
    | '/chamados/novo'
    | '/clientes/$clienteId'
    | '/base-de-conhecimento/'
    | '/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AtualizacoesRoute: typeof AtualizacoesRoute
  BaseDeConhecimentoRoute: typeof BaseDeConhecimentoRouteWithChildren
  CalendarioRoute: typeof CalendarioRoute
  ChamadosRoute: typeof ChamadosRouteWithChildren
  FrotaRoute: typeof FrotaRoute
  IniciarHadronRoute: typeof IniciarHadronRoute
  KanbanRoute: typeof KanbanRoute
  KanbanDashboardRoute: typeof KanbanDashboardRoute
  MinhaContaRoute: typeof MinhaContaRoute
  VersoesRoute: typeof VersoesRoute
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizacoes': {
      id: '/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AtualizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-de-conhecimento': {
      id: '/base-de-conhecimento'
      path: '/base-de-conhecimento'
      fullPath: '/base-de-conhecimento'
      preLoaderRoute: typeof BaseDeConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota': {
      id: '/frota'
      path: '/frota'
      fullPath: '/frota'
      preLoaderRoute: typeof FrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-hadron': {
      id: '/iniciar-hadron'
      path: '/iniciar-hadron'
      fullPath: '/iniciar-hadron'
      preLoaderRoute: typeof IniciarHadronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban-dashboard': {
      id: '/kanban-dashboard'
      path: '/kanban-dashboard'
      fullPath: '/kanban-dashboard'
      preLoaderRoute: typeof KanbanDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versoes': {
      id: '/versoes'
      path: '/versoes'
      fullPath: '/versoes'
      preLoaderRoute: typeof VersoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-de-conhecimento/': {
      id: '/base-de-conhecimento/'
      path: '/'
      fullPath: '/base-de-conhecimento/'
      preLoaderRoute: typeof BaseDeConhecimentoIndexRouteImport
      parentRoute: typeof BaseDeConhecimentoRoute
    }
    '/base-de-conhecimento/$slug': {
      id: '/base-de-conhecimento/$slug'
      path: '/$slug'
      fullPath: '/base-de-conhecimento/$slug'
      preLoaderRoute: typeof BaseDeConhecimentoSlugRouteImport
      parentRoute: typeof BaseDeConhecimentoRoute
    }
    '/chamados/novo': {
      id: '/chamados/novo'
      path: '/novo'
      fullPath: '/chamados/novo'
      preLoaderRoute: typeof ChamadosNovoRouteImport
      parentRoute: typeof ChamadosRoute
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BaseDeConhecimentoRouteChildren {
  BaseDeConhecimentoSlugRoute: typeof BaseDeConhecimentoSlugRoute
  BaseDeConhecimentoIndexRoute: typeof BaseDeConhecimentoIndexRoute
}

const BaseDeConhecimentoRouteChildren: BaseDeConhecimentoRouteChildren = {
  BaseDeConhecimentoSlugRoute: BaseDeConhecimentoSlugRoute,
  BaseDeConhecimentoIndexRoute: BaseDeConhecimentoIndexRoute,
}

const BaseDeConhecimentoRouteWithChildren =
  BaseDeConhecimentoRoute._addFileChildren(BaseDeConhecimentoRouteChildren)

interface ChamadosRouteChildren {
  ChamadosNovoRoute: typeof ChamadosNovoRoute
}

const ChamadosRouteChildren: ChamadosRouteChildren = {
  ChamadosNovoRoute: ChamadosNovoRoute,
}

const ChamadosRouteWithChildren = ChamadosRoute._addFileChildren(
  ChamadosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AtualizacoesRoute: AtualizacoesRoute,
  BaseDeConhecimentoRoute: BaseDeConhecimentoRouteWithChildren,
  CalendarioRoute: CalendarioRoute,
  ChamadosRoute: ChamadosRouteWithChildren,
  FrotaRoute: FrotaRoute,
  IniciarHadronRoute: IniciarHadronRoute,
  KanbanRoute: KanbanRoute,
  KanbanDashboardRoute: KanbanDashboardRoute,
  MinhaContaRoute: MinhaContaRoute,
  VersoesRoute: VersoesRoute,
  ClientesClienteIdRoute: ClientesClienteIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
