/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersoesRouteImport } from './routes/versoes'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as KanbanDashboardRouteImport } from './routes/kanban-dashboard'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as BaseDeConhecimentoRouteImport } from './routes/base-de-conhecimento'
import { Route as AtualizacoesRouteImport } from './routes/atualizacoes'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaseDeConhecimentoIndexRouteImport } from './routes/base-de-conhecimento.index'
import { Route as ChamadosNovoRouteImport } from './routes/chamados.novo'
import { Route as BaseDeConhecimentoSlugRouteImport } from './routes/base-de-conhecimento.$slug'

const VersoesRoute = VersoesRouteImport.update({
  id: '/versoes',
  path: '/versoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanDashboardRoute = KanbanDashboardRouteImport.update({
  id: '/kanban-dashboard',
  path: '/kanban-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseDeConhecimentoRoute = BaseDeConhecimentoRouteImport.update({
  id: '/base-de-conhecimento',
  path: '/base-de-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizacoesRoute = AtualizacoesRouteImport.update({
  id: '/atualizacoes',
  path: '/atualizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseDeConhecimentoIndexRoute = BaseDeConhecimentoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseDeConhecimentoRoute,
} as any)
const ChamadosNovoRoute = ChamadosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ChamadosRoute,
} as any)
const BaseDeConhecimentoSlugRoute = BaseDeConhecimentoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BaseDeConhecimentoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/base-de-conhecimento': typeof BaseDeConhecimentoRouteWithChildren
  '/chamados': typeof ChamadosRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/kanban': typeof KanbanRoute
  '/kanban-dashboard': typeof KanbanDashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/versoes': typeof VersoesRoute
  '/base-de-conhecimento/$slug': typeof BaseDeConhecimentoSlugRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/base-de-conhecimento/': typeof BaseDeConhecimentoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/chamados': typeof ChamadosRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/kanban': typeof KanbanRoute
  '/kanban-dashboard': typeof KanbanDashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/versoes': typeof VersoesRoute
  '/base-de-conhecimento/$slug': typeof BaseDeConhecimentoSlugRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/base-de-conhecimento': typeof BaseDeConhecimentoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/base-de-conhecimento': typeof BaseDeConhecimentoRouteWithChildren
  '/chamados': typeof ChamadosRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/kanban': typeof KanbanRoute
  '/kanban-dashboard': typeof KanbanDashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/versoes': typeof VersoesRoute
  '/base-de-conhecimento/$slug': typeof BaseDeConhecimentoSlugRoute
  '/chamados/novo': typeof ChamadosNovoRoute
  '/base-de-conhecimento/': typeof BaseDeConhecimentoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/atualizacoes'
    | '/base-de-conhecimento'
    | '/chamados'
    | '/clientes'
    | '/kanban'
    | '/kanban-dashboard'
    | '/minha-conta'
    | '/versoes'
    | '/base-de-conhecimento/$slug'
    | '/chamados/novo'
    | '/base-de-conhecimento/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/atualizacoes'
    | '/chamados'
    | '/clientes'
    | '/kanban'
    | '/kanban-dashboard'
    | '/minha-conta'
    | '/versoes'
    | '/base-de-conhecimento/$slug'
    | '/chamados/novo'
    | '/base-de-conhecimento'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/atualizacoes'
    | '/base-de-conhecimento'
    | '/chamados'
    | '/clientes'
    | '/kanban'
    | '/kanban-dashboard'
    | '/minha-conta'
    | '/versoes'
    | '/base-de-conhecimento/$slug'
    | '/chamados/novo'
    | '/base-de-conhecimento/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AtualizacoesRoute: typeof AtualizacoesRoute
  BaseDeConhecimentoRoute: typeof BaseDeConhecimentoRouteWithChildren
  ChamadosRoute: typeof ChamadosRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  KanbanRoute: typeof KanbanRoute
  KanbanDashboardRoute: typeof KanbanDashboardRoute
  MinhaContaRoute: typeof MinhaContaRoute
  VersoesRoute: typeof VersoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/versoes': {
      id: '/versoes'
      path: '/versoes'
      fullPath: '/versoes'
      preLoaderRoute: typeof VersoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban-dashboard': {
      id: '/kanban-dashboard'
      path: '/kanban-dashboard'
      fullPath: '/kanban-dashboard'
      preLoaderRoute: typeof KanbanDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-de-conhecimento': {
      id: '/base-de-conhecimento'
      path: '/base-de-conhecimento'
      fullPath: '/base-de-conhecimento'
      preLoaderRoute: typeof BaseDeConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizacoes': {
      id: '/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AtualizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-de-conhecimento/': {
      id: '/base-de-conhecimento/'
      path: '/'
      fullPath: '/base-de-conhecimento/'
      preLoaderRoute: typeof BaseDeConhecimentoIndexRouteImport
      parentRoute: typeof BaseDeConhecimentoRoute
    }
    '/chamados/novo': {
      id: '/chamados/novo'
      path: '/novo'
      fullPath: '/chamados/novo'
      preLoaderRoute: typeof ChamadosNovoRouteImport
      parentRoute: typeof ChamadosRoute
    }
    '/base-de-conhecimento/$slug': {
      id: '/base-de-conhecimento/$slug'
      path: '/$slug'
      fullPath: '/base-de-conhecimento/$slug'
      preLoaderRoute: typeof BaseDeConhecimentoSlugRouteImport
      parentRoute: typeof BaseDeConhecimentoRoute
    }
  }
}

interface BaseDeConhecimentoRouteChildren {
  BaseDeConhecimentoSlugRoute: typeof BaseDeConhecimentoSlugRoute
  BaseDeConhecimentoIndexRoute: typeof BaseDeConhecimentoIndexRoute
}

const BaseDeConhecimentoRouteChildren: BaseDeConhecimentoRouteChildren = {
  BaseDeConhecimentoSlugRoute: BaseDeConhecimentoSlugRoute,
  BaseDeConhecimentoIndexRoute: BaseDeConhecimentoIndexRoute,
}

const BaseDeConhecimentoRouteWithChildren =
  BaseDeConhecimentoRoute._addFileChildren(BaseDeConhecimentoRouteChildren)

interface ChamadosRouteChildren {
  ChamadosNovoRoute: typeof ChamadosNovoRoute
}

const ChamadosRouteChildren: ChamadosRouteChildren = {
  ChamadosNovoRoute: ChamadosNovoRoute,
}

const ChamadosRouteWithChildren = ChamadosRoute._addFileChildren(
  ChamadosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AtualizacoesRoute: AtualizacoesRoute,
  BaseDeConhecimentoRoute: BaseDeConhecimentoRouteWithChildren,
  ChamadosRoute: ChamadosRouteWithChildren,
  ClientesRoute: ClientesRoute,
  KanbanRoute: KanbanRoute,
  KanbanDashboardRoute: KanbanDashboardRoute,
  MinhaContaRoute: MinhaContaRoute,
  VersoesRoute: VersoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
