// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import {
  supabasePublishableKey,
  supabaseProjectId,
  supabaseUrl,
} from 'virtual:crm-supabase-config';

const CRM_SUPABASE_PROJECT_REF = 'vbkbbfeujqmvgmmhmeao';

function assertCrmSupabaseUrl(value: string): void {
  const hostname = new URL(value).hostname;
  if (!hostname.startsWith(`${CRM_SUPABASE_PROJECT_REF}.`)) {
    throw new Error('A aplicação não está conectada ao projeto CRM Prócion.');
  }
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  const SUPABASE_URL = supabaseUrl;
  const SUPABASE_PUBLISHABLE_KEY = supabasePublishableKey;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || !supabaseProjectId) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (supabaseProjectId !== CRM_SUPABASE_PROJECT_REF) {
    throw new Error('A configuração não pertence ao projeto CRM Prócion.');
  }

  assertCrmSupabaseUrl(SUPABASE_URL);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

